apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

namespace: prd

images:
  - name: abhilashindulkar/linux-tweet-app
    newName: abhilashindulkar/linux-tweet-app
    newTag: "v0.02"

commonLabels:
  environment: production

nameSuffix: -prd
