apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## importing base config
  - ../base/
  ## one way to define all the resources without importing the base config.
  # - namespace.yml
  # - deployment.yml
  # - service.yml

# patches:
#   - patch-file.yml

namespace: uat

commonLabels:
  environment: uat-operational

nameSuffix: -uat
