apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-sample-webapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: tomcat-webapp-container
        image: abhilashindulkar/tomcat-sample-app
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
