kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
    paths:
    - path: /tweet
      pathType: Prefix
      backend:
        service:
          name: linux-tweet-app-service
        port:
          number: 80
