apiVersion: v1
kind: Service
metadata:
  name: linux-tweet-app-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tweet
